version: 2.1
executors:
  zephyr-docker:
    docker:
      - image: jmgao/zephyr-docker:20201113

jobs:
  build:
    executor: zephyr-docker
    parameters:
      board:
        description: "Board to build"
        type: string
    environment:
      BOARD: << parameters.board >>
    steps:
      - checkout
      - run:
          name: Fetch source
          command: "/fetch.sh -p passinglink"
      - run:
          name: Build << parameters.board >>
          command: "cd /zephyr/passinglink; /zephyr/passinglink/scripts/build.sh"
      - run:
          name: Copy binary to workspace
          command: "mkdir /workspace && cp /zephyr/passinglink/build/<< parameters.board >>/pl.bin /workspace/<< parameters.board >>.bin"
      - persist_to_workspace:
          root: /workspace
          paths: "<< parameters.board >>.bin"

  package:
    docker:
      - image: circleci/buildpack-deps:bionic
    steps:
      - run: mkdir -p /tmp/workspace
      - attach_workspace:
          at: /tmp/workspace
      - store_artifacts:
          path: /tmp/workspace
          destination: /

workflows:
  version: 2
  build:
    jobs:
      - build:
          name: build_pl_e73
          board: pl_e73
      - build:
          name: build_pl_dongle
          board: pl_dongle
      - build:
          name: build_pl_bluepill
          board: pl_bluepill
      - build:
          name: build_stm32f4_disco
          board: stm32f4_disco
      - package:
          requires:
            - build_pl_e73
            - build_pl_dongle
            - build_pl_bluepill
            - build_stm32f4_disco
